# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Tail
version:      0.99.3
version_from: Tail.pm.debug
installdirs:  site
requires:
    File::stat:                    0
    FileHandle:                    0
    IO::Seekable:                  0
    Time::HiRes:                   1.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
